### ISSUE TITLE
Decide theme topic for website

### ISSUE THREAD

**Issue by vwashington** [team-cs4300/team-project#1]
We need to brain storm what this page should be about.

**Comment by KevinHa59** [comment]
the first thing we need to decide is, do we need to use database?

**Comment by vwashington** [comment]
> the first thing we need to decide is, do we need to use database?

I dont know, I feel like we will understand the use of a database if we understand our topic of choice. I suggest something simple which would require a database. So like a store or restaurant.

**Comment by KevinHa59** [comment]
Store or restaurant is not easy. I have never tried to build store or restaurant on Website platform, but I had tried to build them on desktop platform with Java and SQL, and there are a lot of things we need to due with.  

This is my suggestion, just create a website that help user create their own portfolio/resume, they will input their information and output with the style they want, we can create several styles that they can pick.

**Comment by trisavo** [comment]
What do you mean? this class is purely frontend we can make a showcase of a restaurant and users can click through the photos/prices. Databases/backend is completely optional, so why don't we do the bare minimum and have a working frontend? I can do fancy effects like enlarge to hover/ pretty animations. 


@KevinHa59 a website that helps users create their own portfolio is hard because they would have to export it and our website would have to generate code and it would have to go somewhere.. We would also have to manage file upload which is a whole ordeal.. 

I think a multi-page website with a firebase backend (i heard that's easy to set up) and pretty css is the way to go? no need for user login/ authentication or anything

**Comment by vwashington** [comment]
What about an application tracker? Basically the person can keep a list of where they put in job applications and their status. I assume this can be done with a firebase backend. Its actually useful for college students.

**Comment by trisavo** [comment]
it already exists, im pretty sure..but still thats going to require a ton of work ... are you looking to use this as a project for your resume?

if you want to go that route we can just copy an existing application tracker and reskin the frontend

**Comment by vwashington** [comment]
No, for your question. Im just issuing an idea, thats the point here. We can build a Todo-List, a simple game such as hangman using any theme. You mentioned a game guide, how do we incorporate the server-side scripting language?

**Comment by vwashington** [comment]
Seems we agree on creating a website for show weather information once the city is entered.
